spring:
  data:
    mongodb:
      host: ds129166.mlab.com
      port: 29166
      database: pictureci-arsw
      username: pictureci
      password: pictureci
  redis:
    host: 127.0.0.1
    port: 6379
    #password:
